version: '3.8'

services:
  web:
    image: "avito_segments:latest"
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=dynamic_user_segmentation
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - ./create_table.sql:/docker-entrypoint-initdb.d/init.sql